Select and move multiple mods
soda3x/ArmaReforgerServerTool pull request #91
Opened 2024-09-22 20:54 UTC by benfleuty

This PR alters the move mod logic to allow multiple items in the added/enabled list boxes to be selected. When the `>` or `<` buttons are clicked, all selected mods are moved to the appropriate list.

This will close #90.

2024-09-22 21:06 UTC, benfleuty commented on ArmaReforgerServerTool/Forms/Main.Designer.cs
A lot of auto-gen code has changed here for the UI. I don't see any changes visually.

2024-09-22 23:34 UTC, soda3x commented
let me know when you want me to look at it

2024-09-23 11:38 UTC, benfleuty commented
Ready for a review now!

2024-09-25 04:01 UTC, soda3x requested changes

2024-09-25 15:49 UTC, benfleuty commented on ArmaReforgerServerTool/Forms/Main.cs
> +            Mod[] modsToMove = new Mod[GetAvailableModsList().SelectedItems.Count];
I don't see a benefit to using a List over Array here. The number of items is known every time. Array will have a smaller memory footprint.

Array will also be slightly faster access-wise.

2024-09-25 15:54 UTC, benfleuty commented on ArmaReforgerServerTool/Managers/ConfigurationManager.cs
>              // Determine whether Rcon should be included in the server configuration
Are you using any plugins? Could you add an .editorconfig from `Options > Text Editor > C# > Code Style` if not. That'll force everyone onto the same code style. I am using VS 2022 defaults currently.

2024-09-25 21:13 UTC, soda3x commented on ArmaReforgerServerTool/Forms/Main.cs
> +            Mod[] modsToMove = new Mod[GetAvailableModsList().SelectedItems.Count];
Yeah that's all fine, no worries. I don't really mind which way it's done. Lists are just more flexible which I think outweighs the performance aspect for an application like this. Fine with you leaving as-is.

2024-09-25 21:13 UTC, soda3x commented on ArmaReforgerServerTool/Managers/ConfigurationManager.cs
>              // Determine whether Rcon should be included in the server configuration
I also use defaults because I've just not bothered to create a formatter preset. I probably should, you're right.

2024-09-25 21:16 UTC, benfleuty commented on ArmaReforgerServerTool/Managers/ConfigurationManager.cs
>              // Determine whether Rcon should be included in the server configuration
Visual Studio sure is hell for going back in history so I will do it manually and push soon™️ .

2024-09-25 22:36 UTC, benfleuty commented on ArmaReforgerServerTool/Managers/ConfigurationManager.cs
>              // Determine whether Rcon should be included in the server configuration
This 100% needs to be automagically enforced since it is non-standard. Presumably this was the formatter running... 🤷

2024-09-25 23:04 UTC, benfleuty commented
Setting the ListBoxes to MultiExtended is changing a lot of the UI by a little bit. Doesn't look any different though. That should be most if not all the formatting done. Inconsistencies in spacing around casts. Opted for `(type) variable`.

2024-09-25 23:07 UTC, soda3x commented
When I can, I will pull this and have a play with it, code looks good now, just a matter of trying it out on my behalf :)

2024-10-04 23:14 UTC, soda3x commented
Tested, looks good

2024-10-04 23:14 UTC, soda3x approved these changes
Ready for merge!

2024-10-04 23:14 UTC, merged